### ISSUE TITLE
[REQUEST] render 함수들 위치를 js폴더로 옮기는게 어떨까요?

### ISSUE THREAD

**Issue by to06109** [likelion-js-project4/taing#164]
# Issue: 개발 로직 변경 요청

## 문제상황
각종 리스트를 render하는 함수들이 lib폴더에 들어가 있어서 실제 라이브러리 파일을 보는게 불편합니다. 
![image](https://user-images.githubusercontent.com/69625013/216995356-6324a2de-6e8e-4441-8d1c-6b6d7ccaf704.png)

## 요청사항
render함수들을 js폴더 안의 render라는 폴더를 만들어서 따로 관리하는게 어떨까요?
![image](https://user-images.githubusercontent.com/69625013/216995433-5fd7f055-4193-430a-9417-e7d0efd1a921.png)

**Comment by cf9874** [comment]
저도 이거 생각했던건데 좋은 것 같습니다

**Comment by dydgh142** [comment]
좋습니다
